In [1]:
import pandas as pd

Importing Dataset

In [ ]:
df = pd.read_excel("/content/Data - Survey Monkey Output.xlsx",sheet_name="Edited_Data")
df

Created a copy of our dataset incase we need to revert back

In [3]:
df_modified = df.copy()
df_modified

,Respondent ID,Start Date,End Date,Email Address,First Name,Last Name,Custom Data 1,Identify which division you work in. - Response,Identify which division you work in. - Other (please specify),Which of the following best describes your position level? - Response,...,Question 29 - Response 8,Question 29 - Response 9,Question 29 - Response 10,Question 29 - Response 11,Question 29 - Response 12,Question 29 - Response 13,Question 29 - Response 14,Question 30 - Response 1,Question 30 - Response 2,Question 30 - Response 3
0,5379192392,2021-01-22 12:01:17,2021-01-22 12:40:34,NaN,NaN,NaN,NaN,Infrastructure,NaN,Staff,...,NaN,Answer 8,Answer 8,Answer 4,NaN,NaN,Answer 5,NaN,NaN,NaN
1,2658722536,2021-01-22 06:56:37,2021-01-22 07:34:10,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,NaN,Answer 5,NaN,NaN,Answer 2,NaN,Answer 5,NaN,NaN,Answer 1
2,4044163394,2021-01-22 06:35:18,2021-01-22 06:47:32,NaN,NaN,NaN,NaN,Infrastructure,NaN,Department Lead,...,NaN,NaN,Answer 4,Answer 4,Answer 6,NaN,Answer 6,NaN,Answer 1,NaN
3,5535865599,2021-01-21 21:29:32,2021-01-21 21:40:24,NaN,NaN,NaN,NaN,Infrastructure,NaN,Manager,...,Answer 2,Answer 5,Answer 7,NaN,Answer 6,NaN,Answer 7,Answer 7,Answer 1,Answer 6
4,3356802928,2021-01-21 17:26:39,2021-01-21 17:44:40,NaN,NaN,NaN,NaN,Port Operations,NaN,Manager,...,NaN,Answer 5,Answer 4,Answer 4,Answer 7,Answer 7,NaN,Answer 7,NaN,Answer 8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,7940065082,2021-01-11 06:19:18,2021-01-11 06:32:59,NaN,NaN,NaN,NaN,Infrastructure,NaN,Department Lead,...,Answer 1,Answer 1,Answer 3,Answer 6,Answer 6,Answer 8,NaN,NaN,NaN,Answer 8
194,5157705612,2021-01-11 06:19:14,2021-01-11 06:33:29,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,Answer 5,NaN,Answer 5,NaN,NaN,Answer 2,NaN,NaN,NaN,Answer 6
195,9920755555,2021-01-11 06:18:48,2021-01-11 06:27:27,NaN,NaN,NaN,NaN,Port Operations,NaN,Staff,...,NaN,Answer 7,NaN,NaN,NaN,NaN,NaN,NaN,Answer 3,NaN
196,6638341389,2021-01-11 06:19:01,2021-01-11 06:33:06,NaN,NaN,NaN,NaN,Infrastructure,NaN,Manager,...,Answer 2,NaN,Answer 3,Answer 5,NaN,Answer 8,Answer 3,Answer 3,NaN,NaN
197,8114622230,2021-01-11 06:18:50,2021-01-11 06:26:46,NaN,NaN,NaN,NaN,Information Technology,NaN,Staff,...,Answer 3,NaN,Answer 7,NaN,NaN,NaN,NaN,Answer 3,NaN,NaN

In [4]:
df_modified.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 100 columns):
 #   Column                                                                         Non-Null Count  Dtype
---  ------                                                                         --------------  -----
 0   Respondent ID                                                                  198 non-null    int64
 1   Start Date                                                                     198 non-null    datetime64[ns]
 2   End Date                                                                       198 non-null    datetime64[ns]
 3   Email Address                                                                  0 non-null      float64
 4   First Name                                                                     0 non-null      float64
 5   Last Name                                                                      0 non-null      float64
 6   Custom Data 1                                                                  0 non-null      float64
 7   Identify which division you work in. - Response                                197 non-null    object
 8   Identify which division you work in. - Other (please specify)                  2 non-null      object
 9   Which of the following best describes your position level? - Response          196 non-null    object
 10  Which generation are you apart of? - Response                                  196 non-null    object
 11  Please select the gender in which you identify. - Response                     196 non-null    object
 12  Which duration range best aligns with your tenure at your company? - Response  198 non-null    object
 13  Which of the following best describes your employment type? - Response         198 non-null    object
 14  Question 1 - Response                                                          119 non-null    object
 15  Question 2 - Response                                                          118 non-null    object
 16  Question 3 - Open-Ended Response                                               117 non-null    object
 17  Question 4 - Response                                                          116 non-null    object
 18  Question 4 - Other (please specify)                                            104 non-null    object
 19  Question 5 - Response 1                                                        118 non-null    object
 20  Question 5 - Response 2                                                        112 non-null    object
 21  Question 5 - Response 3                                                        109 non-null    object
 22  Question 5 - Response 4                                                        112 non-null    object
 23  Question 5 - Response 5                                                        111 non-null    object
 24  Question 5 - Response 6                                                        114 non-null    object
 25  Question 6 - Response 1                                                        116 non-null    object
 26  Question 6 - Response 2                                                        104 non-null    object
 27  Question 6 - Response 3                                                        116 non-null    object
 28  Question 6 - Response 4                                                        105 non-null    object
 29  Question 6 - Response 5                                                        116 non-null    object
 30  Question 6 - Response 6                                                        107 non-null    object
 31  Question 7 - Response 1                                                        118 non-null    object
 32  Question 7 - Unscheduled                                                       119 non-null    object
 33  Question 8 - Response 1                                                        117 non-null    object
 34  Question 8 - Response 2                                                        115 non-null    object
 35  Question 8 - Response 3                                                        110 non-null    object
 36  Question 8 - Response 4                                                        104 non-null    object
 37  Question 9 - Response 1                                                        121 non-null    object
 38  Question 9 - Response 2                                                        113 non-null    object
 39  Question 9 - Response 3                                                        108 non-null    object
 40  Question 9 - Response 4                                                        111 non-null    object
 41  Question 10 - Response 1                                                       113 non-null    object
 42  Question 10 - Response 2                                                       117 non-null    object
 43  Question 10 - Response 3                                                       123 non-null    object
 44  Question 10 - Response 4                                                       107 non-null    object
 45  Question 10 - Response 5                                                       125 non-null    object
 46  Question 11 - Reponse 1                                                        122 non-null    object
 47  Question 11 - Response 2                                                       117 non-null    object
 48  Question 12 - Response                                                         114 non-null    object
 49  Question 13 - Response                                                         108 non-null    object
 50  Question 14 - Response                                                         105 non-null    object
 51  Question 15 - Response                                                         114 non-null    object
 52  Question 16 - Response                                                         117 non-null    object
 53  Question 17 - Response                                                         135 non-null    object
 54  Question 18 - Response                                                         109 non-null    object
 55  Question 19 - Response                                                         119 non-null    object
 56  Question 19 - Other (please specify)                                           107 non-null    object
 57  Question 20 - Response                                                         105 non-null    object
 58  Question 21 - Response                                                         127 non-null    object
 59  Question 22 - Reponse 1                                                        107 non-null    object
 60  Question 22 - Reponse 2                                                        107 non-null    object
 61  Question 23 - Response                                                         120 non-null    object
 62  Question 24 - Response 1                                                       111 non-null    object
 63  Question 24 - Response 2                                                       110 non-null    object
 64  Question 24 - Response 3                                                       105 non-null    object
 65  Question 24 - Response 4                                                       107 non-null    object
 66  Question 24 - Response 5                                                       111 non-null    object
 67  Question 25 - Response 1                                                       105 non-null    object
 68  Question 25 - Response 2                                                       102 non-null    object
 69  Question 25 - Response 3                                                       107 non-null    object
 70  Question 25 - Response 4                                                       113 non-null    object
 71  Question 25 - Response 5                                                       106 non-null    object
 72  Question 25 - Response 6                                                       116 non-null    object
 73  Question 25 - Response 7                                                       107 non-null    object
 74  Question 25 - Response 8                                                       108 non-null    object
 75  Question 25 - Response 9                                                       106 non-null    object
 76  Question 26 - Response 1                                                       100 non-null    object
 77  Question 26 - Response 2                                                       119 non-null    object
 78  Question 26 - Response 3                                                       107 non-null    object
 79  Question 26 - Response 4                                                       110 non-null    object
 80  Question 27 - Response 1                                                       106 non-null    object
 81  Question 27 - Response 2                                                       105 non-null    object
 82  Question 28 - Response                                                         119 non-null    object
 83  Question 29 - Response 1                                                       120 non-null    object
 84  Question 29 - Response 2                                                       112 non-null    object
 85  Question 29 - Response 3                                                       108 non-null    object
 86  Question 29 - Response 4                                                       114 non-null    object
 87  Question 29 - Response 5                                                       107 non-null    object
 88  Question 29 - Response 6                                                       115 non-null    object
 89  Question 29 - Response 7                                                       112 non-null    object
 90  Question 29 - Response 8                                                       113 non-null    object
 91  Question 29 - Response 9                                                       123 non-null    object
 92  Question 29 - Response 10                                                      106 non-null    object
 93  Question 29 - Response 11                                                      115 non-null    object
 94  Question 29 - Response 12                                                      103 non-null    object
 95  Question 29 - Response 13                                                      120 non-null    object
 96  Question 29 - Response 14                                                      116 non-null    object
 97  Question 30 - Response 1                                                       103 non-null    object
 98  Question 30 - Response 2                                                       117 non-null    object
 99  Question 30 - Response 3                                                       112 non-null    object
dtypes: datetime64[ns](2), float64(4), int64(1), object(93)
memory usage: 154.8+ KB

In [5]:
df_modified.columns

Index(['Respondent ID', 'Start Date', 'End Date', 'Email Address',
       'First Name', 'Last Name', 'Custom Data 1',
       'Identify which division you work in. - Response',
       'Identify which division you work in. - Other (please specify)',
       'Which of the following best describes your position level? - Response',
       'Which generation are you apart of? - Response',
       'Please select the gender in which you identify. - Response',
       'Which duration range best aligns with your tenure at your company? - Response',
       'Which of the following best describes your employment type? - Response',
       'Question 1 - Response', 'Question 2 - Response',
       'Question 3 - Open-Ended Response', 'Question 4 - Response',
       'Question 4 - Other (please specify)', 'Question 5 - Response 1',
       'Question 5 - Response 2', 'Question 5 - Response 3',
       'Question 5 - Response 4', 'Question 5 - Response 5',
       'Question 5 - Response 6', 'Question 6 - Response 1',
       'Question 6 - Response 2', 'Question 6 - Response 3',
       'Question 6 - Response 4', 'Question 6 - Response 5',
       'Question 6 - Response 6', 'Question 7 - Response 1',
       'Question 7 - Unscheduled', 'Question 8 - Response 1',
       'Question 8 - Response 2', 'Question 8 - Response 3',
       'Question 8 - Response 4', 'Question 9 - Response 1',
       'Question 9 - Response 2', 'Question 9 - Response 3',
       'Question 9 - Response 4', 'Question 10 - Response 1',
       'Question 10 - Response 2', 'Question 10 - Response 3',
       'Question 10 - Response 4', 'Question 10 - Response 5',
       'Question 11 - Reponse 1', 'Question 11 - Response 2',
       'Question 12 - Response', 'Question 13 - Response',
       'Question 14 - Response', 'Question 15 - Response',
       'Question 16 - Response', 'Question 17 - Response',
       'Question 18 - Response', 'Question 19 - Response',
       'Question 19 - Other (please specify)', 'Question 20 - Response',
       'Question 21 - Response', 'Question 22 - Reponse 1',
       'Question 22 - Reponse 2', 'Question 23 - Response',
       'Question 24 - Response 1', 'Question 24 - Response 2',
       'Question 24 - Response 3', 'Question 24 - Response 4',
       'Question 24 - Response 5', 'Question 25 - Response 1',
       'Question 25 - Response 2', 'Question 25 - Response 3',
       'Question 25 - Response 4', 'Question 25 - Response 5',
       'Question 25 - Response 6', 'Question 25 - Response 7',
       'Question 25 - Response 8', 'Question 25 - Response 9',
       'Question 26 - Response 1', 'Question 26 - Response 2',
       'Question 26 - Response 3', 'Question 26 - Response 4',
       'Question 27 - Response 1', 'Question 27 - Response 2',
       'Question 28 - Response', 'Question 29 - Response 1',
       'Question 29 - Response 2', 'Question 29 - Response 3',
       'Question 29 - Response 4', 'Question 29 - Response 5',
       'Question 29 - Response 6', 'Question 29 - Response 7',
       'Question 29 - Response 8', 'Question 29 - Response 9',
       'Question 29 - Response 10', 'Question 29 - Response 11',
       'Question 29 - Response 12', 'Question 29 - Response 13',
       'Question 29 - Response 14', 'Question 30 - Response 1',
       'Question 30 - Response 2', 'Question 30 - Response 3'],
      dtype='object')

Dropping columns we dont need

In [6]:
columns_to_drop = ['Start Date', 'End Date', 'Email Address','First Name', 'Last Name', 'Custom Data 1']
columns_to_drop

['Start Date',
 'End Date',
 'Email Address',
 'First Name',
 'Last Name',
 'Custom Data 1']

In [7]:
df_modified.drop(columns = columns_to_drop,inplace = True)

In [8]:
df_modified

,Respondent ID,Identify which division you work in. - Response,Identify which division you work in. - Other (please specify),Which of the following best describes your position level? - Response,Which generation are you apart of? - Response,Please select the gender in which you identify. - Response,Which duration range best aligns with your tenure at your company? - Response,Which of the following best describes your employment type? - Response,Question 1 - Response,Question 2 - Response,...,Question 29 - Response 8,Question 29 - Response 9,Question 29 - Response 10,Question 29 - Response 11,Question 29 - Response 12,Question 29 - Response 13,Question 29 - Response 14,Question 30 - Response 1,Question 30 - Response 2,Question 30 - Response 3
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,NaN,Answer 6,...,NaN,Answer 8,Answer 8,Answer 4,NaN,NaN,Answer 5,NaN,NaN,NaN
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Answer 4,Answer 2,...,NaN,Answer 5,NaN,NaN,Answer 2,NaN,Answer 5,NaN,NaN,Answer 1
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Answer 5,Answer 7,...,NaN,NaN,Answer 4,Answer 4,Answer 6,NaN,Answer 6,NaN,Answer 1,NaN
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Answer 1,Answer 1,...,Answer 2,Answer 5,Answer 7,NaN,Answer 6,NaN,Answer 7,Answer 7,Answer 1,Answer 6
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,NaN,Answer 3,...,NaN,Answer 5,Answer 4,Answer 4,Answer 7,Answer 7,NaN,Answer 7,NaN,Answer 8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Answer 3,NaN,...,Answer 1,Answer 1,Answer 3,Answer 6,Answer 6,Answer 8,NaN,NaN,NaN,Answer 8
194,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,NaN,NaN,...,Answer 5,NaN,Answer 5,NaN,NaN,Answer 2,NaN,NaN,NaN,Answer 6
195,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,NaN,Answer 7,...,NaN,Answer 7,NaN,NaN,NaN,NaN,NaN,NaN,Answer 3,NaN
196,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,NaN,NaN,...,Answer 2,NaN,Answer 3,Answer 5,NaN,Answer 8,Answer 3,Answer 3,NaN,NaN
197,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,NaN,Answer 1,...,Answer 3,NaN,Answer 7,NaN,NaN,NaN,NaN,Answer 3,NaN,NaN

Unpivoting our dataframe

In [9]:
id_vars = list(df_modified.columns)[0 : 8]
id_vars

['Respondent ID',
 'Identify which division you work in. - Response',
 'Identify which division you work in. - Other (please specify)',
 'Which of the following best describes your position level? - Response',
 'Which generation are you apart of? - Response',
 'Please select the gender in which you identify. - Response',
 'Which duration range best aligns with your tenure at your company? - Response',
 'Which of the following best describes your employment type? - Response']

In [10]:
value_vars = list(df_modified.columns)[8 : ]
#value_vars

In [11]:
df_melted = pd.melt(df_modified,id_vars=id_vars,value_vars = value_vars,var_name ="Question + Subquestion" ,value_name = "Answer")
df_melted

,Respondent ID,Identify which division you work in. - Response,Identify which division you work in. - Other (please specify),Which of the following best describes your position level? - Response,Which generation are you apart of? - Response,Please select the gender in which you identify. - Response,Which duration range best aligns with your tenure at your company? - Response,Which of the following best describes your employment type? - Response,Question + Subquestion,Answer
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1 - Response,NaN
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1 - Response,Answer 4
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1 - Response,Answer 5
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1 - Response,Answer 1
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1 - Response,NaN
...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30 - Response 3,Answer 8
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30 - Response 3,Answer 6
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,NaN
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,NaN
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30 - Response 3,NaN

In [12]:
df_melted.columns

Index(['Respondent ID', 'Identify which division you work in. - Response',
       'Identify which division you work in. - Other (please specify)',
       'Which of the following best describes your position level? - Response',
       'Which generation are you apart of? - Response',
       'Please select the gender in which you identify. - Response',
       'Which duration range best aligns with your tenure at your company? - Response',
       'Which of the following best describes your employment type? - Response',
       'Question + Subquestion', 'Answer'],
      dtype='object')

In [ ]:
df_melted_2 = df_melted.copy()
df_melted_2

Created a Seperate column which only contains Questions

In [17]:
df_melted_2[["Question", "to_drop"]] = df_melted_2["Question + Subquestion"].str.split(" - ", expand=True)

In [19]:
df_melted_2.drop(columns = "to_drop",inplace = True)
df_melted_2

,Respondent ID,Identify which division you work in. - Response,Identify which division you work in. - Other (please specify),Which of the following best describes your position level? - Response,Which generation are you apart of? - Response,Please select the gender in which you identify. - Response,Which duration range best aligns with your tenure at your company? - Response,Which of the following best describes your employment type? - Response,Question + Subquestion,Answer,Question
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1 - Response,NaN,Question 1
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1 - Response,Answer 4,Question 1
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1 - Response,Answer 5,Question 1
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1 - Response,Answer 1,Question 1
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1 - Response,NaN,Question 1
...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30 - Response 3,Answer 8,Question 30
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30 - Response 3,Answer 6,Question 30
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,NaN,Question 30
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,NaN,Question 30
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30 - Response 3,NaN,Question 30

Finding number of people responded for a question

In [31]:
respondents = df_melted_2[df_melted_2["Answer"].notna()]
respondents = respondents.groupby("Question")["Respondent ID"].nunique().reset_index()

In [32]:
respondents.rename(columns={"Respondent ID":"Respondents"},inplace = True)
respondents

       Question  Respondents
0    Question 1          119
1   Question 10          198
2   Question 11          164
3   Question 12          114
4   Question 13          108
5   Question 14          105
6   Question 15          114
7   Question 16          117
8   Question 17          135
9   Question 18          109
10  Question 19          157
11   Question 2          118
12  Question 20          105
13  Question 21          127
14  Question 22          160
15  Question 23          120
16  Question 24          195
17  Question 25          198
18  Question 26          193
19  Question 27          153
20  Question 28          119
21  Question 29          198
22   Question 3          117
23  Question 30          182
24   Question 4          161
25   Question 5          194
26   Question 6          196
27   Question 7          162
28   Question 8          190
29   Question 9          188

In [33]:
df_merged = pd.merge(df_melted_2,respondents,how="left" ,left_on="Question" , right_on="Question" ,)
print("Before",len(df_melted_2))
print("After",len(df_merged))
df_merged

Before 17028
After 17028

,Respondent ID,Identify which division you work in. - Response,Identify which division you work in. - Other (please specify),Which of the following best describes your position level? - Response,Which generation are you apart of? - Response,Please select the gender in which you identify. - Response,Which duration range best aligns with your tenure at your company? - Response,Which of the following best describes your employment type? - Response,Question + Subquestion,Answer,Question,Respondents
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1 - Response,NaN,Question 1,119
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1 - Response,Answer 4,Question 1,119
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1 - Response,Answer 5,Question 1,119
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1 - Response,Answer 1,Question 1,119
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1 - Response,NaN,Question 1,119
...,...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30 - Response 3,Answer 8,Question 30,182
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30 - Response 3,Answer 6,Question 30,182
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,NaN,Question 30,182
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,NaN,Question 30,182
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30 - Response 3,NaN,Question 30,182

Finding Number of people gave same answer per question

In [34]:
same_answer = df_melted_2 # [df_melted_2["Answer"].notna()]
same_answer = same_answer.groupby(["Question + Subquestion","Answer"])["Respondent ID"].nunique().reset_index()
same_answer.rename(columns={"Respondent ID":"Same Answer"},inplace = True)
same_answer

      Question + Subquestion    Answer  Same Answer
0      Question 1 - Response  Answer 1           14
1      Question 1 - Response  Answer 2           10
2      Question 1 - Response  Answer 3           13
3      Question 1 - Response  Answer 4           17
4      Question 1 - Response  Answer 5           22
..                       ...       ...          ...
683  Question 9 - Response 4  Answer 4           16
684  Question 9 - Response 4  Answer 5           13
685  Question 9 - Response 4  Answer 6           14
686  Question 9 - Response 4  Answer 7           12
687  Question 9 - Response 4  Answer 8           19

[688 rows x 3 columns]

In [36]:
df_merged_2 = pd.merge(df_merged,same_answer,how="left" ,left_on=["Question + Subquestion","Answer"] , right_on=["Question + Subquestion","Answer"] ,)
print("Before",len(df_merged))
print("After",len(df_merged_2))
df_merged_2

Before 17028
After 17028

,Respondent ID,Identify which division you work in. - Response,Identify which division you work in. - Other (please specify),Which of the following best describes your position level? - Response,Which generation are you apart of? - Response,Please select the gender in which you identify. - Response,Which duration range best aligns with your tenure at your company? - Response,Which of the following best describes your employment type? - Response,Question + Subquestion,Answer,Question,Respondents,Same Answer
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1 - Response,NaN,Question 1,119,NaN
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1 - Response,Answer 4,Question 1,119,17.0
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1 - Response,Answer 5,Question 1,119,22.0
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1 - Response,Answer 1,Question 1,119,14.0
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1 - Response,NaN,Question 1,119,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30 - Response 3,Answer 8,Question 30,182,14.0
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30 - Response 3,Answer 6,Question 30,182,20.0
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,NaN,Question 30,182,NaN
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,NaN,Question 30,182,NaN
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30 - Response 3,NaN,Question 30,182,NaN

Filling Nan with 0 in Same Answer Cloumn

In [41]:
df_merged_2["Same Answer"].fillna(0,inplace = True)
df_merged_2["Answer"].fillna("Not Answered",inplace = True)
df_merged_2

,Respondent ID,Identify which division you work in. - Response,Identify which division you work in. - Other (please specify),Which of the following best describes your position level? - Response,Which generation are you apart of? - Response,Please select the gender in which you identify. - Response,Which duration range best aligns with your tenure at your company? - Response,Which of the following best describes your employment type? - Response,Question + Subquestion,Answer,Question,Respondents,Same Answer
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1 - Response,Not Answered,Question 1,119,0.0
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1 - Response,Answer 4,Question 1,119,17.0
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1 - Response,Answer 5,Question 1,119,22.0
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1 - Response,Answer 1,Question 1,119,14.0
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1 - Response,Not Answered,Question 1,119,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30 - Response 3,Answer 8,Question 30,182,14.0
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30 - Response 3,Answer 6,Question 30,182,20.0
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,Not Answered,Question 30,182,0.0
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,Not Answered,Question 30,182,0.0
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30 - Response 3,Not Answered,Question 30,182,0.0

In [40]:
df_merged_2.columns

Index(['Respondent ID', 'Identify which division you work in. - Response',
       'Identify which division you work in. - Other (please specify)',
       'Which of the following best describes your position level? - Response',
       'Which generation are you apart of? - Response',
       'Please select the gender in which you identify. - Response',
       'Which duration range best aligns with your tenure at your company? - Response',
       'Which of the following best describes your employment type? - Response',
       'Question + Subquestion', 'Answer', 'Question', 'Respondents',
       'Same Answer'],
      dtype='object')

Renaming column Headers

In [42]:
df_cleaned_1 = df_merged_2.copy()
df_cleaned_1.rename(columns = {'Identify which division you work in. - Response':"Division Primary",
       'Identify which division you work in. - Other (please specify)':"Division Secondary",
       'Which of the following best describes your position level? - Response':"Position",
       'Which generation are you apart of? - Response':"Generation",
       'Please select the gender in which you identify. - Response':"Gender",
       'Which duration range best aligns with your tenure at your company? - Response':"Tenure",
       'Which of the following best describes your employment type? - Response':"Employment Type"},inplace = True)
df_cleaned_1

,Respondent ID,Division Primary,Division Secondary,Position,Generation,Gender,Tenure,Employment Type,Question + Subquestion,Answer,Question,Respondents,Same Answer
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1 - Response,Not Answered,Question 1,119,0.0
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1 - Response,Answer 4,Question 1,119,17.0
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1 - Response,Answer 5,Question 1,119,22.0
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1 - Response,Answer 1,Question 1,119,14.0
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1 - Response,Not Answered,Question 1,119,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30 - Response 3,Answer 8,Question 30,182,14.0
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30 - Response 3,Answer 6,Question 30,182,20.0
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,Not Answered,Question 30,182,0.0
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,Not Answered,Question 30,182,0.0
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30 - Response 3,Not Answered,Question 30,182,0.0

In [44]:
df_cleaned_1.columns

Index(['Respondent ID', 'Division Primary', 'Division Secondary', 'Position',
       'Generation', 'Gender', 'Tenure', 'Employment Type',
       'Question + Subquestion', 'Answer', 'Question', 'Respondents',
       'Same Answer'],
      dtype='object')

Combining Divsion primary and Division Secondary Columns

In [64]:
df_cleaned_2 = df_cleaned_1.copy()
df_cleaned_2['Division Primary'] = df_cleaned_2.apply(lambda row: row['Division Secondary'] if pd.notna(row['Division Primary']) and row['Division Primary'] == 'Other (please specify)' else row['Division Primary'], axis=1)
df_cleaned_2

,Respondent ID,Division Primary,Division Secondary,Position,Generation,Gender,Tenure,Employment Type,Question + Subquestion,Answer,Question,Respondents,Same Answer
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1 - Response,Not Answered,Question 1,119,0.0
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1 - Response,Answer 4,Question 1,119,17.0
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1 - Response,Answer 5,Question 1,119,22.0
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1 - Response,Answer 1,Question 1,119,14.0
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1 - Response,Not Answered,Question 1,119,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30 - Response 3,Answer 8,Question 30,182,14.0
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30 - Response 3,Answer 6,Question 30,182,20.0
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,Not Answered,Question 30,182,0.0
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,Not Answered,Question 30,182,0.0
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30 - Response 3,Not Answered,Question 30,182,0.0

In [65]:
df_cleaned_2[df_cleaned_2["Division Secondary"].notna()]["Division Secondary"]

13        Construction
98       Rather not say
211       Construction
296      Rather not say
409       Construction
              ...
16532    Rather not say
16645     Construction
16730    Rather not say
16843     Construction
16928    Rather not say
Name: Division Secondary, Length: 172, dtype: object

Cross checked,  
two people ansered as "other(specify)" = 2  
total quetion+subqutions = 86   
2*86 = 172

In [68]:
df_cleaned_2.drop(columns= "Division Secondary",inplace = True)
df_cleaned_2

,Respondent ID,Division Primary,Position,Generation,Gender,Tenure,Employment Type,Question + Subquestion,Answer,Question,Respondents,Same Answer
0,5379192392,Infrastructure,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1 - Response,Not Answered,Question 1,119,0.0
1,2658722536,Finance,Staff,NaN,NaN,10+ years,Full time Employee,Question 1 - Response,Answer 4,Question 1,119,17.0
2,4044163394,Infrastructure,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1 - Response,Answer 5,Question 1,119,22.0
3,5535865599,Infrastructure,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1 - Response,Answer 1,Question 1,119,14.0
4,3356802928,Port Operations,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1 - Response,Not Answered,Question 1,119,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30 - Response 3,Answer 8,Question 30,182,14.0
17024,5157705612,Finance,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30 - Response 3,Answer 6,Question 30,182,20.0
17025,9920755555,Port Operations,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,Not Answered,Question 30,182,0.0
17026,6638341389,Infrastructure,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30 - Response 3,Not Answered,Question 30,182,0.0
17027,8114622230,Information Technology,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30 - Response 3,Not Answered,Question 30,182,0.0

In [70]:
df_cleaned_2.iloc[16532]

Respondent ID                                        6225804357
Division Primary                                 Rather not say
Position                                                Manager
Generation                Generation X (born between 1965-1980)
Gender                                     Prefer not to answer
Tenure                                                10+ years
Employment Type                              Full time Employee
Question + Subquestion                 Question 30 - Response 1
Answer                                                 Answer 5
Question                                            Question 30
Respondents                                                 182
Same Answer                                                19.0
Name: 16532, dtype: object

Exporting to excel file

In [72]:
df_cleaned_2.to_excel("/content/Final_output_SurveyMonkey.xlsx",index = False)